dependencies {
    implementation project(":hilingual-external")
    implementation project(":hilingual-common")
    implementation project(":hilingual-auth")

    // database
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Bouncy Castle Provider
    implementation 'org.bouncycastle:bcprov-jdk18on:1.81'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.81'

    // OAuth
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'com.google.oauth-client:google-oauth-client-java6:1.36.0'
    implementation 'com.google.oauth-client:google-oauth-client-jetty:1.36.0'
    implementation 'com.google.api-client:google-api-client:2.4.0'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'

    // Webflux
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

}

bootJar { enabled = false }
jar { enabled = true }
