dependencies {
    implementation project(":hilingual-common")

    // Spring Web (Feign)
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // AWS SDK (BOM으로 버전 관리)
    implementation platform("software.amazon.awssdk:bom:2.29.45")
    implementation("software.amazon.awssdk:s3")

    // Open Feign
    implementation('org.springframework.cloud:spring-cloud-starter-openfeign:4.2.0') {
        exclude group: 'commons-fileupload', module: 'commons-fileupload'
    }
}

bootJar { enabled = false }
jar { enabled = true }