package org.hilingual.domain.diary.api.service.diff;

public class DiaryFeedbackPrompt {

     public static final String PROMPT =
             "영어공부가 목적인 한국인의 영어 일기입니다. 사용자가 작성한 영어 일기를 읽고 다음 세 가지 작업을 순서대로 정확하게 수행하세요.\n"
                     + "\n"
                     + "---\n"
                     + "\n"
                     + "### **1. 철자와 문법 오류만 교정한 전체 일기를 반환하세요. (rewriteText)**\n"
                     + "\n"
                     + "- 오직 **문법(Grammar)** 및 **철자(Spelling)** 오류만 교정해주세요.\n"
                     + "- 교정할 오류가 없다면 **원문을 그대로 반환**하세요.\n"
                     + "- 일기 중 **한국어로 작성한 부분은 영어로 번역**해주세요.\n"
                     + "\n"
                     + "### **2. 철자 또는 문법 오류가 있었던 문장을 최대 5개까지 반환하세요. (feedbackList)\n"
                     + "\n"
                     + "- 각 문장마다 다음 정보를 **반드시 포함**하세요:\n"
                     + "    - **original**: 틀린 문장 (사용자가 작성한 원문)\n"
                     + "    - **rewrite**: 교정된 문장\n"
                     + "    - **explain**: 교정 이유 설명 (한국어로 1~2문장)\n"
                     + "- feedbackList 반환 기준:\n"
                     + "    - 쉼표 추가 및 삭제, 대소문자 구분, 하이픈 추가 및 삭제는 feedbackList에서 제외하세요.\n"
                     + "    - 한국어에서 영어로 번역한 부분은 feedbackList에서 **제외하세요.**\n"
                     + "    - rewriteText에서 교정한 철자와 문법 오류가 5개 이상이라면 feedbackList에서 무조건 5개를 반환하세요.\n"
                     + "- explain 작성 시 유의사항:\n"
                     + "    - **친절한 말투로 설명해주세요.**\n"
                     + "    - 철자와 문법을 수정한 구체적인 근거와 이유를 설명해주세요.\n"
                     + "- 예시\n"
                     + "\n"
                     + "original: I think I have a lot of people who gave positive impact on my life.\n"
                     + "\n"
                     + "rewrite: I think I have a lot of people who have had a positive impact on my life.\n"
                     + "\n"
                     + "explain: “현재까지 영향을 미친 사람들을 말하고 있으므로 현재완료형 ‘have had’를 사용해야 자연스럽습니다.”\n"
                     + "\n"
                     + "---\n"
                     + "\n"
                     + "### **3. 추천할 영어 표현(최소 5개 ~ 최대 8개)을 반환하세요. (phraseList)\n"
                     + "\n"
                     + "- 원문 일기에 사용된 표현은 절대 추천하지 마세요.\n"
                     + "- 원문 일기와 어울리는 새로운 단어와 표현을 추천하세요.\n"
                     + "- 각 표현은 아래 정보를 반드시 포함하세요:\n"
                     + "    - **phrase** : 추천 표현 (영어)\n"
                     + "    - **phraseType** : 품사 목록 (명사, 대명사, 동사, 형용사, 부사, 전치사, 접속사, 감탄사 중 택) + 필요시 숙어, 속어, 구 중 하나 추가\n"
                     + "    - **explanation** : 자연스럽고 정확한 **한국어 의미**\n"
                     + "    - **reason:** 예문 포함 + 일기와 어울리는 이유 설명 (예문은 \"큰 따옴표\" 사용)\n"
                     + "- 예시\n"
                     + "\n"
                     + "phrase: resonate with\n"
                     + "phraseType: 동사, 숙어\n"
                     + "explanation: ~와 깊이 공감되다, 마음에 와닿다\n"
                     + "reason: “Their lyrics really resonate with me.”처럼 사용하면 감정적인 연결을 강조할 수 있어요.\n"
                     + "\n"
                     + "---\n"
                     + "\n"
                     + "### **4. 결과는 반드시 아래 JSON 형식으로 반환하세요:**\n"
                     + "\n"
                     + "{\n"
                     + "  \"rewriteText\": \"교정된 전체 일기 (또는 원문 그대로)\",\n"
                     + "  \"feedbackList\": [\n"
                     + "    {\n"
                     + "      \"original\": \"틀린 문장\",\n"
                     + "      \"rewrite\": \"교정된 문장\",\n"
                     + "      \"explain\": \"교정 이유 (한국어)\"\n"
                     + "    }\n"
                     + "  ],\n"
                     + "  \"phraseList\": [\n"
                     + "    {\n"
                     + "      \"phrase\": \"추천 표현\",\n"
                     + "      \"phraseType\": [\"동사\", \"숙어\"],\n"
                     + "      \"explanation\": \"추천 표현에 대한 한국어 설명\",\n"
                     + "      \"reason\": \"해당 표현을 추천한 이유\"\n"
                     + "    }\n"
                     + "  ]\n"
                     + "}\n";
}