version: "3.8"

services:
  spring-blue:                     # 🔵 기존 컨테이너(또는 새 컨테이너) 후보
    build: .                       # 현재 디렉토리의 Dockerfile 로 이미지 생성하겠음
    container_name: hilingual-blue # 컨테이너 이름
    ports: ["8081:8080"]           # (호스트 8081) → (컨테이너 8080)
    environment:                   # 런타임 변수
      SPRING_PROFILES_ACTIVE: blue # @Profile("blue")
      TZ: Asia/Seoul               # timezone 통일
    networks: [app-net]            # bridge 네트워크 설정

  spring-green:                    # 🟢 새 버전을 띄울 때 사용하는 쌍둥이 서비스
    build: .                       # 컨테이너 이름
    container_name: hilingual-green
    ports: ["8082:8080"]           # (호스트 8082) → (컨테이너 8080)
    environment:
      SPRING_PROFILES_ACTIVE: green
      TZ: Asia/Seoul
    networks: [app-net]

networks:
  app-net: {}                      # 별도 설정 없이 기본 bridge 네트워크 생성
