services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hilingual-app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://hilingual-db.c5kyca0ay63n.ap-northeast-2.rds.amazonaws.com:3306/dev?serverTimezone=Asia/Seoul
      - DB_ID=admin
      - DB_PW=hilingual614

  nginx:
    image: nginx:latest
    container_name: hilingual-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
