version: '3.8'

services:
  spring-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hilingual-blue
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=blue
    networks:
      - hilingual-network

  spring-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hilingual-green
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=green
    networks:
      - hilingual-network

  nginx:
    image: nginx:latest
    container_name: hilingual-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.env:/etc/nginx/.env
    environment:
      - deployment_target=${deployment_target}
    depends_on:
      - spring-blue
      - spring-green
    networks:
      - hilingual-network

networks:
  hilingual-network:
    driver: bridge

