version: '3.8'

services:
  spring-blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hilingual-blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
      - DB_URL=${DB_URL}
      - DB_ID=${DB_ID}
      - DB_PW=${DB_PW}

  spring-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hilingual-green
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=green
      - DB_URL=${DB_URL}
      - DB_ID=${DB_ID}
      - DB_PW=${DB_PW}

  nginx:
    image: nginx:latest
    container_name: hilingual-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.env:/etc/nginx/.env
    environment:
      - deployment_target
