pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }

    plugins {
        id "com.autonomousapps.dependency-analysis" version "1.29.0"
    }
}

rootProject.name = 'hilingual-server'

include 'hilingual-api'
include 'hilingual-domain'
include 'hilingual-common'
include 'hilingual-auth'
include 'hilingual-external'