spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  file:
    name: /home/ubuntu/logs/app.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

---

spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: green
server:
  port: 8081

