spring:
  application:
    name: securityTest

  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email

logging:
  file:
    name: /home/ubuntu/logs/app.log

jwt:
  secret-key: ${SECRET_KEY}
  access-expiration-seconds: ${ACCESS_EXPIRATION}
  refresh-expiration-seconds: ${REFRESH_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

aws-property:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  aws-region: ${AWS_REGION}
  bucket-name: ${AWS_BUCKET_NAME}

openai:
  api-key: ${OPENAI_API_KEY}

---

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  config:
    activate:
      on-profile: blue
server:
  port: 8080

---

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  config:
    activate:
      on-profile: green

