server {
    listen 80;

    # 애플리케이션 Blue/Green
    location / {
        proxy_pass http://${TARGET_UPSTREAM};
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 헬스체크
    location /healthz {
        proxy_pass http://${TARGET_UPSTREAM}/actuator/health;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /grafana {
        return 302 /grafana/;
    }

    rewrite ^/prometheus$ /prometheus/ permanent;
    rewrite ^/loki$ /loki/ permanent;

    # Grafana (monitoring EC2: 10.0.2.54:3000)
    location /grafana/ {
        proxy_pass http://10.0.2.54:3000/grafana/;   # nginx경유 IP:PORT
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /grafana;
        proxy_redirect off;
    }

    # Prometheus (monitoring EC2: 10.0.2.54:9090)
    location /prometheus/ {
        proxy_pass http://10.0.2.54:9090/prometheus/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Loki (monitoring EC2: 10.0.2.54:3100)
    location /loki/ {
        proxy_pass http://10.0.2.54:3100/;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
