# ── api.hilingual.kr (운영, HTTP만)
server {
  listen 80;
  server_name api.hilingual.kr;

  include /etc/nginx/includes/prod.inc;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  return 308 https://$host$request_uri;
}

# ── api-dev.hilingual.kr (개발, HTTP만)
server {
  listen 80;
  server_name api-dev.hilingual.kr;

  include /etc/nginx/includes/dev.inc;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  return 308 https://$host$request_uri;
}
