-- V14__create_recovery_ticket.sql

create table if not exists recovery_ticket
(
    id           bigint generated by default as identity primary key,
    user_id      bigint       not null references users,
    written_date date         not null,
    is_used      boolean      not null default false,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6),
    constraint uk_recovery_ticket_user_written_date unique (user_id, written_date)
);

alter table recovery_ticket owner to hilingual;