-- V1__init_schema.sql  (Hilingual)
-- 초기 스키마: Dev/Prod 모두 비어있는 DB에 최초 적용

-- (1) USERS
create table if not exists users
(
    id              bigint generated by default as identity primary key,
    provider        varchar(20)           not null,
    provider_id     varchar(255)          not null,
    role            varchar(255)
    constraint users_role_check
    check ((role)::text = any ((array['USER'::varchar, 'ADMIN'::varchar])::text[])),
    register_status integer               not null,
    notify_status   boolean               not null,
    is_deleted      boolean default false not null,
    created_at      timestamp(6)          not null,
    updated_at      timestamp(6),
    deleted_at      timestamp(6),

    unique (provider, provider_id)
    );
alter table users owner to hilingual;

-- (2) NOTICE_DETAIL
create table if not exists notice_detail
(
    id      bigint generated by default as identity primary key,
    content text not null
);
alter table notice_detail owner to hilingual;

-- (3) NOTICE
create table if not exists notice
(
    id               bigint generated by default as identity primary key,
    title            varchar(100) not null,
    category         integer      not null,
    is_active        boolean      not null,
    created_at       timestamp(6) not null,
    updated_at       timestamp(6),
    notice_detail_id bigint       not null unique
    references notice_detail
    );
alter table notice owner to hilingual;

-- (4) TOPIC
create table if not exists topic
(
    date      date not null primary key,
    topic_en  varchar(255),
    topic_kor varchar(255)
    );
alter table topic owner to hilingual;

-- (5) FORBIDDEN_WORD
create table if not exists forbidden_word
(
    id             bigint generated by default as identity primary key,
    forbidden_word varchar(50)
    );
alter table forbidden_word owner to hilingual;

-- (6) ALARM_PREFERENCE
create table if not exists alarm_preference
(
    id         bigint generated by default as identity primary key,
    user_id    bigint  not null references users,
    alarm_type integer not null,
    is_enabled boolean not null,
    constraint uk_alarm_type_user_id unique (alarm_type, user_id)
    );
alter table alarm_preference owner to hilingual;

-- (7) BLOCK
create table if not exists block
(
    id         bigint generated by default as identity primary key,
    blocker_id bigint not null references users,
    blocked_id bigint not null references users,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    constraint uk_blocked_blocker unique (blocker_id, blocked_id)
    );
alter table block owner to hilingual;

-- (8) DIARY
create table if not exists diary
(
    id            bigint generated by default as identity primary key,
    user_id       bigint        not null references users,
    is_public     boolean       not null,
    is_liked      integer       not null,
    written_date  date,
    original_text varchar(1000) not null,
    rewrite_text  varchar(1500) not null,
    image_url     varchar(255),
    shared_time   timestamp(6),
    created_at    timestamp(6)  not null,
    updated_at    timestamp(6)
    );
alter table diary owner to hilingual;

-- (9) DIARY_FEEDBACK
create table if not exists diary_feedback
(
    id             bigint generated by default as identity primary key,
    diary_id       bigint       not null references diary,
    version        integer      not null,
    origin_phrase  varchar(255),
    rewrite_phrase varchar(255) not null,
    explanation    varchar(255) not null,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6)
    );
alter table diary_feedback owner to hilingual;

-- (10) FEED_ALARM
create table if not exists feed_alarm
(
    id          bigint generated by default as identity primary key,
    user_id     bigint       not null references users,
    actor_id    bigint       not null,
    target_id   bigint       not null,
    target_type integer      not null,
    type        integer      not null,
    title       varchar(100) not null,
    read_at     timestamp(6),
    created_at  timestamp(6) not null,
    updated_at  timestamp(6)
    );
alter table feed_alarm owner to hilingual;

-- (11) FOLLOW
create table if not exists follow
(
    id          bigint generated by default as identity primary key,
    follower_id bigint not null references users,
    followee_id bigint not null references users,
    created_at  timestamp(6) not null,
    updated_at  timestamp(6),
    constraint uk_follower_followee unique (follower_id, followee_id)
    );
alter table follow owner to hilingual;

-- (12) LIKED_DIARY
create table if not exists liked_diary
(
    id         bigint generated by default as identity primary key,
    user_id    bigint not null references users,
    diary_id   bigint not null references diary,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    constraint uk_user_diary unique (user_id, diary_id)
    );
alter table liked_diary owner to hilingual;

-- (13) RECOMMEND
create table if not exists recommend
(
    id            bigint generated by default as identity primary key,
    diary_id      bigint       not null references diary,
    phrase        varchar(255) not null,
    phrase_type   varchar(255) not null,
    explanation   varchar(255) not null,
    reason        varchar(255) not null,
    is_bookmarked boolean      not null,
    created_at    timestamp(6) not null,
    updated_at    timestamp(6)
    );
alter table recommend owner to hilingual;

-- (14) NOTICE_DELIVERY
create table if not exists notice_delivery
(
    id           bigint generated by default as identity primary key,
    notice_id    bigint not null references notice,
    user_id      bigint not null references users,
    delivered_at timestamp(6) not null,
    read_at      timestamp(6),
    constraint uk_notice_delivery_notice_user unique (notice_id, user_id)
    );
alter table notice_delivery owner to hilingual;

-- (15) USER_CALENDAR
create table if not exists user_calendar
(
    id         bigint generated by default as identity primary key,
    user_id    bigint not null references users,
    date       date not null,
    status     varchar(16) not null
    constraint user_calendar_status_check
    check ((status)::text = any ((array['NONE'::varchar, 'WRITTEN'::varchar, 'DELETED'::varchar])::text[])),
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    unique (user_id, date)
    );
alter table user_calendar owner to hilingual;

-- (16) USER_PROFILE
create table if not exists user_profile
(
    id             bigint generated by default as identity primary key,
    user_id        bigint       not null unique references users,
    nickname       varchar(20)  not null unique,
    profile_img    varchar(512),
    streak         integer      not null,
    total_diaries  integer      not null,
    user_follower  integer      not null,
    user_following integer      not null,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6)
    );
alter table user_profile owner to hilingual;

-- (17) VOCA
create table if not exists voca
(
    id           bigint generated by default as identity primary key,
    user_id      bigint not null references users,
    recommend_id bigint not null,
    phrase       varchar(255) not null,
    phrase_type  varchar(255) not null,
    explanation  varchar(255) not null,
    written_from varchar(255) not null,
    saved_root   integer      not null,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6),
    constraint uk_voca_user_recommend unique (user_id, recommend_id)
    );
alter table voca owner to hilingual;

-- (18) INDEXES
create index if not exists idx_alarm_preference_user   on alarm_preference (user_id);
create index if not exists idx_block_blocker           on block (blocker_id);
create index if not exists idx_block_blocked           on block (blocked_id);
create index if not exists idx_diary_user              on diary (user_id);
create index if not exists idx_diary_feedback_diary    on diary_feedback (diary_id);
create index if not exists idx_feed_alarm_user         on feed_alarm (user_id);
create index if not exists idx_feed_alarm_actor        on feed_alarm (actor_id);
create index if not exists idx_follow_follower         on follow (follower_id);
create index if not exists idx_follow_followee         on follow (followee_id);
create index if not exists idx_liked_diary_user        on liked_diary (user_id);
create index if not exists idx_liked_diary_diary       on liked_diary (diary_id);
create index if not exists idx_notice_delivery_notice  on notice_delivery (notice_id);
create index if not exists idx_notice_delivery_user    on notice_delivery (user_id);
create index if not exists idx_recommend_diary         on recommend (diary_id);
create index if not exists idx_user_calendar_user_date on user_calendar (user_id, date);
create index if not exists idx_user_profile_user       on user_profile (user_id);
create index if not exists idx_voca_user               on voca (user_id);
create index if not exists idx_voca_recommend          on voca (recommend_id);