-- V3__add_device_table.sql

create table if not exists device
(
    id            bigint generated by default as identity primary key,
    user_id       bigint                not null,
    uuid          varchar(255)          not null,
    timezone      varchar(100),
    device_name   varchar(255),
    device_type   varchar(50)
    constraint device_type_check
    check ((device_type)::text = any ((array['PHONE'::varchar, 'TABLET'::varchar, 'DESKTOP'::varchar])::text[])),
    os_type       varchar(50),
    os_version    varchar(50),
    app_version   varchar(50),
    created_at    timestamp(6)          not null,
    updated_at    timestamp(6),

    constraint fk_device_user foreign key (user_id) references users (id),

    unique (user_id, uuid) --
    );

alter table device owner to hilingual;